### ISSUE TITLE
Initial to-do list

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/dendrite_ynh#1]
# To-do list before marking the app as working.

YunoHost scripts:
- [x] Upgrade
- [x] Backup and restore
- [x] Change URL
- [x] ~~Fix SSO login for Element~~ (not yet implemented by Matrix, let's use a config panel)

Dendrite features:
- ~~TURN server (reuse what Synapse does?, package a global TURN server for YunoHost?)~~ not needed anymore?
- ~~(optional) Offer to reuse encryption key from Synapse (https://github.com/matrix-org/dendrite/blob/master/docs/serverkeyformat.md). That's important to avoid that irritating `(@user:server.tld)` addendum after the username when the same username is used twice in one room.~~ seems not to be an issue

Feel free to create dedicated issues if some tasks require brainstorming/assistance.

**Comment by tomdereub** [comment]
For the turn server, you could use this app I think : https://github.com/YunoHost-Apps/coturn_ynh

**Comment by Gredin67** [comment]
is there a workaround to connect a user in element through its yunohost username? I'm getting
`Incorrect username and/or password.`

**Comment by tituspijean** [comment]
So, I have just had a look back into this app, installed from https://github.com/YunoHost-Apps/dendrite_ynh/pull/14.

I had to:
- [ ] work around the open registration warning by adding `--really-enable-open-registration` to the service ExecStart command. We need to investigate a proper registration scheme. I think LDAP is not yet integrated with Dendrite, @Gredin67 
- [ ] add a custom rule for ssowat in `/etc/ssowat/conf.json.persistent` (cf. below)
It should be added with the permissions helpers
- [ ] Add a bunch of CORS settings because Element was yelling all over the place and was unable to connect (cf. below)

```json
        "dendrite.server_api": {
            "auth_header": false,
            "label": "Dendrite (Server access for client apps.)",
            "public": true,
            "show_tile": false,
            "uris": [
                "<dendrite domain>/_matrix"
            ],
            "users": []
        }
```

```conf
# /etc/nginx/conf.d/dendrite.pijean.ovh.d/dendrite.conf
rewrite ^$ /;
location ~ ^/$ {
    default_type text/plain;
    return 200 "This is where Dendrite is installed.";
}

location /.well-known/matrix/server {
        default_type application/json;
    return 200 '{ "m.server": "dendrite.pijean.ovh:443" }';
    more_set_headers "Access-Control-Allow-Origin: *";
}

location /.well-known/matrix/client {
    return 200 '{ "m.homeserver": { "base_url": "https://dendrite.pijean.ovh" } }';
    more_set_headers "Access-Control-Allow-Origin: *";
}

location /_matrix {
    proxy_pass http://localhost:8008;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host            $host;
    proxy_read_timeout               600;
    client_max_body_size             100M;
    more_set_headers "Access-Control-Allow-Origin: *";
}
```
